const PATH = {
    home: "/",
    login: "/login",
    stacks: "/stacks",
    stacksMore: "/stacks/:stackId",
    stacksMoreByGroupMore: "/stacks/:stackId/:id",
    stacksMoreByGroupUpdate: "/stacks/:stackId/:id/update",
    stacksGroupCreate: "/stacks/:stackId/create",
    stacksCreate: "/stacks/create",
    stacksUpdate: "/stacks/:stackId/update",
    groups: "/groups",
    groupsMore: "/groups/:id",
    groupsMoreByStudentsMore: "/groups/:groupId/:id",
    groupsMoreByStudentsUpdate: "/groups/:groupId/:id/update",
    groupsStudentsCreate: "/groups/:groupId/create",
    groupsUpdate: "/groups/:id/update",
    groupsCreate: "/groups/create",
    teachers: "/teachers",
    teachersMoreByGroupMore: "/teachers/:teacherId/:id",
    teachersMoreByGroupUpdate: "/teachers/:teacherId/:id/update",
    teachersGroupCreate: "/teachers/:teacherId/create",
    teachersMore: "/teachers/:id",
    teachersUpdate: "/teachers/:id/update",
    teachersCreate: "/teachers/create",
    students: "/students",
    studentsMore: "/students/:id",
    studentsUpdate: "/students/:id/update",
    studentsCreate: "/students/create",
    rooms: "/rooms",
    roomsMore: "/rooms/:id",
    roomsUpdate: "/rooms/:id/update",
    roomsCreate: "/rooms/create",
    users: "/users",
    usersMore: "/users/:id",
    usersUpdate: "/users/:id/update",
    usersCreate: "/users/create",
    notFound: "*"
}

export default PATH